### ISSUE TITLE
Header covering top third

### ISSUE THREAD

**Issue by jonmost** [jonmost/jonmost.github.io#116]
I can't activate the buttons when located on top third of the page. It appears the body padding is covering the buttons. When I move the </header> to the bottom of the page I can access the buttons but loose the ability to scroll. @alexose can you help?

**Comment by jonmost** [comment]
@BrianLefler I think this is similar to what happened when you helped me build the header. Not sure how you resolved it last time, but if you have a chance could you give it a look as well? I have cleaned up the code significantly so it should be much easier to work with

**Comment by jonmost** [comment]
I have been able to resolve on all pages except "Discover IT" This may be a matter of how high the buttons are on the page but I am not sure

**Comment by BrianLefler** [comment]
"Discover IT" looks good to me.  I fixed up the favicons to show properly now, that "Favicons" snippet needs to be at the head of each page for it to work.

**Comment by jonmost** [comment]
@BrianLefler yeah the problem is still there. It depends on how high up the buttons are located. the problem currently exists on discover and contribute pages

**Comment by jonmost** [comment]
@BrianLefler this is still an issue if you have time. If not let me know and I will see if I can bother someone else :)

**Comment by BrianLefler** [comment]
Taking a look this afternoon when I get into JP.  If you're there in person
it'd be nice to see what you're seeing.  I think I'm looking in the wrong
place.

On Tue, Apr 5, 2016 at 2:13 PM, Jonathan Mostowski <notifications@github.com

**Comment by jonmost** [comment]
Sorry, I was not able to be there to meet with you. Maybe we can connect over the phone. In simple terms I can not select buttons that appear in the upper 3rd of the page main content (not including side nave or header). The only page this is not apparent by attempting to click the first available button is on "Discuss IT" and that is because the first button is lower on the page.

**Comment by jonmost** [comment]
@BrianLefler where you able to take a look at the invisible layer issue?

**Comment by BrianLefler** [comment]
Yes.  I have a theory but am struggling to make Jekyll do what want I want it to do.  I think the <body> tag in the html needs to be <body class="visual-style">, but this line is not obviously present in the md files for me to fix.

**Comment by BrianLefler** [comment]
Fixed.  More complicated than I thought, but what we sorely needed was a layout that made the content better conform to the proper html spec.

We now have that.  Now that we have that, I may move a bunch of duplicative code into one place, so we only have things like the header and the favicons defined in one place in the code, written once and reused many times.

**Comment by BrianLefler** [comment]
I have assigning back to Jon, so he can close this issue if and only if it is actually fixed.  I misunderstood the issue before, so I want to double check.

**Comment by jonmost** [comment]
@BrianLefler Thank you soooo much. At some point I would like to better understand the problem, but I can't thank you enough for all of your help! When we are both round I would like to buy you lunch or a drink to say thanks.

**Comment by BrianLefler** [comment]
Real simple:

- A big strength of the internet is browsers are very permissive and will accept a lot of variation or even outright mistakes in HTML files, and they'll do their best to muddle through.  But browsers sometimes behave weirdly or differently at the edges.
- HTML pages are usually supposed to have \<head\> and \<body\> sections (head for metadata/scripts/favicons, body for content).  When it didn't find it, browsers correctly added a body section and put everything in it, but chrome & safari did something weird to make that new body section have a transparent layer over it.
- Fixed by adding the missing tags.  Instead of writing the same thing 5 times, I added a layout, which is a template all pages now use.
